config/routes.rb
Lab2::Application.routes.draw do

  root 'facultys#index'

  get "search/by_group"
  get "search/by_group_result"

  resources :groups

  resources :facultys

  resources :lessons
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_many :groups, dependent: :destroy
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :faculty

  has_many :lessons, dependent: :destroy

  def self.search(search)
	    if search
	    	find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
	    else
	    	find(:all)
	    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/facultys_controller.rb
class FacultysController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]


	def new
		@faculty = Faculty.new
	end

    def create
    	@faculty = Faculty.new(faculty_params)
 
        if @faculty.save
            redirect_to @faculty
	    else
	        render 'new'
	    end
    end

	def edit
	    @faculty = Faculty.find(params[:id])
	end

	def update
	    @faculty = Faculty.find(params[:id])
	 
	    if @faculty.update(faculty_params)
	        redirect_to @faculty
	    else
	        render 'edit'
	    end
	end

    def show
        @faculty = Faculty.find(params[:id])
    end

    def index
        @facultys = Faculty.all
    end

	def destroy
	  	@faculty = Faculty.find(params[:id])
	  	@faculty.destroy
	 
	  	redirect_to facultys_path
	end

    private
	    def faculty_params
	        params.require(:faculty).permit(:number, :name)
	    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]


	def new
		@group = Group.new
		@faculty = Faculty.find(params[:faculty_id])
	end

    def create
    	@group = Group.new(group_params)
 
        if @group.save
            redirect_to @group
	    else
	        render 'new'
	    end
    end

	def edit
	    @group = Group.find(params[:id])
	end

	def update
	    @group = Group.find(params[:id])
	 
	    if @group.update(group_params)
	        redirect_to @group
	    else
	        render 'edit'
	    end
	end

    def show
        @group = Group.find(params[:id])
	  	@faculty = Faculty.find(@group.faculty_id)
	  	@days = ["Monday",
	        "Tuesday",
	        "Wednesday",
	        "Thursday",
	        "Friday",
	        "Saturday"]
    end

	def destroy
	  	@group = Group.find(params[:id])
	  	@faculty = Faculty.find(@group.faculty_id)
	  	@group.destroy
	 
	  	redirect_to @faculty
	end

    private
	    def group_params
	        params.require(:group).permit(:cource, :name, :faculty_id)
	    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]


	def new
		@lesson = Lesson.new
		@group = Group.find(params[:group_id])
	end

    def create
    	@lesson = Lesson.new(lesson_params)
 
        if @lesson.save
            redirect_to @lesson
	    else
	        render 'new'
	    end
    end

	def edit
	    @lesson = Lesson.find(params[:id])
	end

	def update
	    @lesson = Lesson.find(params[:id])
	 
	    if @lesson.update(lesson_params)
	        redirect_to @lesson
	    else
	        render 'edit'
	    end
	end

    def show
        @lesson = Lesson.find(params[:id])
	  	@group = Group.find(@lesson.group_id)
	  	@faculty = Faculty.find(@group.faculty_id)
	  	@days = ["Monday",
	        "Tuesday",
	        "Wednesday",
	        "Thursday",
	        "Friday",
	        "Saturday"]
    end

	def destroy
	  	@lesson = Lesson.find(params[:id])
	  	@group = Group.find(@lesson.group_id)
	  	@lesson.destroy
	 
	  	redirect_to @group
	end

    private
	    def lesson_params
	        params.require(:lesson).permit(:teacher, :name, :day, :start, :end, :group_id)
	    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def by_group
	end

	def by_group_result
	  if params[:search] && params[:search] != nil && params[:search] != ""
          @groups = Group.search(params[:search])
          if @groups != nil && @groups.size > 0
      	      @group = @groups.first
			  @days = ["Monday",
	        "Tuesday",
	        "Wednesday",
	        "Thursday",
	        "Friday",
	        "Saturday"]
	      else
	      	  redirect_to search_by_group_path
	      end
	  else
	      redirect_to search_by_group_path
	  end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facultys_helper.rb
module FacultysHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/facultys/edit.html.erb
<h1>Редактирование факультета</h1>
 
<%= form_for :faculty, url: faculty_path(@faculty), method: :patch do |f| %>
  <p>
    <%= f.label :номер %><br>
    <%= f.text_field :number %>
  </p>
 
  <p>
    <%= f.label :название %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit :обновить%>
  </p>
<% end %>

<%= link_to 'Назад', facultys_path %>

app/views/facultys/index.html.erb
<h1>Все факультеты</h1>
<%= link_to 'Создать факультет', new_faculty_path %>&nbsp;&nbsp;
<%= link_to 'Поиск расписания по группам', search_by_group_path %><br><br>

<table>
  <tr>
    <th>Номер</th>
    <th>Название</th>
  </tr>
 
  <% @facultys.each do |faculty| %>
    <tr>
      <td><%= faculty.number %></td>
      <td><%= faculty.name %></td>
      <td><%= link_to 'Просмотреть', faculty_path(faculty) %></td>
      <td><%= link_to 'Редактировать', edit_faculty_path(faculty) %></td>
      <td><%= link_to 'Удалить', faculty_path(faculty),
                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>

app/views/facultys/new.html.erb
<h1>Добавить факультет</h1>

<%= form_for :faculty, url: facultys_path do |f| %>
  <p>
    <%= f.label :номер %><br>
    <%= f.text_field :number %>
  </p>
 
  <p>
    <%= f.label :название %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit :сохранить%>
  </p>
<% end %>

<%= link_to 'Назад', facultys_path %>

app/views/facultys/show.html.erb
<p>
  <h1>Факультет №<%= @faculty.number %></h1>
  <strong>Название:</strong>
  <%= @faculty.name %>&nbsp;&nbsp;
  <%= link_to 'Редактировать', edit_faculty_path(@faculty) %>&nbsp;&nbsp;
  <%= link_to 'Добавить группу', new_group_path(:faculty_id => @faculty.id)%><br><br>
</p>

<strong>Группы:</strong><br><br>

<% @faculty.groups.each do |group| %>
	    <tr>
	      <td><%= group.cource %></td>
	      <td><%= group.name %></td>
	      <td><%= link_to 'Просмотреть', group_path(group) %></td>
	      <td><%= link_to 'Редактировать', edit_group_path(group) %></td>
	      <td><%= link_to 'Удалить', group_path(group),
	                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
	    </tr>
    <br>
<% end %>

<br><br>
<%= link_to 'К списку факультетов', facultys_path %>

app/views/groups/edit.html.erb
<h1>Редактирование группы</h1>
 
<%= form_for :group, url: group_path(@group), method: :patch do |f| %>
  <p>
    <%= f.label :название %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :курс%><br>
    <%= f.text_field :cource %>
  </p>
 
  <p>
    <%= f.submit :обновить%>
  </p>
<% end %>

<%= link_to 'Назад', group_path(@group) %>

app/views/groups/new.html.erb
<h1>Добавить группу</h1>

<%= form_for :group, url: groups_path do |f| %>
  <p>
    <%= f.label :курс %><br>
    <%= f.text_field :cource %>
  </p>
 
  <p>
    <%= f.label :название %><br>
    <%= f.text_field :name %>
  </p>

  <%= f.hidden_field :faculty_id, :value => @faculty.id%>
 
  <p>
    <%= f.submit :сохранить%>
  </p>
<% end %>

<%= link_to 'Назад', faculty_path(@faculty) %>

app/views/groups/show.html.erb
<p>
  <h1>Группа <%= @group.name%></h1>
  <strong>Курс:</strong>
  <%= @group.cource %><br>
</p>

<strong>Расписание:</strong>&nbsp;&nbsp;
<%= link_to 'Редактировать', edit_group_path(@group) %>&nbsp;&nbsp;
<%= link_to 'Добавить пару', new_lesson_path(:group_id => @group.id)%><br><br>
 
<strong>Понедельник:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 1 %>
        &nbsp;&nbsp;
	    <tr>
	      <td><%= lesson.name %></td>
	      <td><%= lesson.teacher %></td>
	      <td><%= lesson.start %></td>
	      <td><%= lesson.end %></td>
	      <td><%= @days[lesson.day - 1] %></td>
	      <td><%= link_to 'Просмотреть', lesson_path(lesson) %></td>
	      <td><%= link_to 'Редактировать', edit_lesson_path(lesson) %></td>
	      <td><%= link_to 'Удалить', lesson_path(lesson),
	                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
	    </tr>
        <br>
    <% end %> 
<% end %>

<strong>Вторник:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 2 %>
        &nbsp;&nbsp;
	    <tr>
	      <td><%= lesson.name %></td>
	      <td><%= lesson.teacher %></td>
	      <td><%= lesson.start %></td>
	      <td><%= lesson.end %></td>
	      <td><%= @days[lesson.day - 1] %></td>
	      <td><%= link_to 'Просмотреть', lesson_path(lesson) %></td>
	      <td><%= link_to 'Редактировать', edit_lesson_path(lesson) %></td>
	      <td><%= link_to 'Удалить', lesson_path(lesson),
	                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
	    </tr>
        <br>
    <% end %>
<% end %>

<strong>Среда:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 3 %>
        &nbsp;&nbsp;
	    <tr>
	      <td><%= lesson.name %></td>
	      <td><%= lesson.teacher %></td>
	      <td><%= lesson.start %></td>
	      <td><%= lesson.end %></td>
	      <td><%= @days[lesson.day - 1] %></td>
	      <td><%= link_to 'Просмотреть', lesson_path(lesson) %></td>
	      <td><%= link_to 'Редактировать', edit_lesson_path(lesson) %></td>
	      <td><%= link_to 'Удалить', lesson_path(lesson),
	                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
	    </tr>
        <br>
    <% end %>
<% end %>

<strong>Четверг:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 4 %>
        &nbsp;&nbsp;
	    <tr>
	      <td><%= lesson.name %></td>
	      <td><%= lesson.teacher %></td>
	      <td><%= lesson.start %></td>
	      <td><%= lesson.end %></td>
	      <td><%= @days[lesson.day - 1] %></td>
	      <td><%= link_to 'Просмотреть', lesson_path(lesson) %></td>
	      <td><%= link_to 'Редактировать', edit_lesson_path(lesson) %></td>
	      <td><%= link_to 'Удалить', lesson_path(lesson),
	                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
	    </tr>
        <br>
    <% end %>
<% end %>

<strong>Пятница:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 5 %>
        &nbsp;&nbsp;
	    <tr>
	      <td><%= lesson.name %></td>
	      <td><%= lesson.teacher %></td>
	      <td><%= lesson.start %></td>
	      <td><%= lesson.end %></td>
	      <td><%= @days[lesson.day - 1] %></td>
	      <td><%= link_to 'Просмотреть', lesson_path(lesson) %></td>
	      <td><%= link_to 'Редактировать', edit_lesson_path(lesson) %></td>
	      <td><%= link_to 'Удалить', lesson_path(lesson),
	                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
	    </tr>
        <br>
    <% end %>
<% end %>

<strong>Суббота:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 6 %>
        &nbsp;&nbsp;
	    <tr>
	      <td><%= lesson.name %></td>
	      <td><%= lesson.teacher %></td>
	      <td><%= lesson.start %></td>
	      <td><%= lesson.end %></td>
	      <td><%= @days[lesson.day - 1] %></td>
	      <td><%= link_to 'Просмотреть', lesson_path(lesson) %></td>
	      <td><%= link_to 'Редактировать', edit_lesson_path(lesson) %></td>
	      <td><%= link_to 'Удалить', lesson_path(lesson),
	                    method: :delete, data: { confirm: 'Вы уверены?' } %></td>
	    </tr>
        <br>
    <% end %>
<% end %>
<br>
<br>

<%= link_to 'Вернуться к факультету', faculty_path(@faculty) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lessons/edit.html.erb
<h1>Редактирование пары</h1>
 
<%= form_for :lesson, url: lesson_path(@lesson), method: :patch do |f| %>
  <p>
    <%= f.label :предмет %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :преподаватель %><br>
    <%= f.text_field :teacher %>
  </p>
  
  <p>
    <%= f.label :день_недели %><br>
    <%= f.select :day, options_for_select([["Понедельник", 1],
        ["Вторник", 2],
        ["Среда", 3],
        ["Четверг", 4],
        ["Пятница", 5],
        ["Суббота", 6]]) %>
  </p>
 
  <p>
    <%= f.label :начало_пары %><br>
    <%= f.text_field :start, :placeholder => "hh:mm" %>
  </p>
 
  <p>
    <%= f.label :окончание_пары %><br>
    <%= f.text_field :end, :placeholder => "hh:mm" %>
  </p>
 
  <p>
    <%= f.submit :обновить %>
  </p>
<% end %>

<%= link_to 'Назад', lesson_path(@lesson) %>

app/views/lessons/new.html.erb
<h1>Добавить пару</h1>

<%= form_for :lesson, url: lessons_path do |f| %>
  <p>
    <%= f.label :предмет %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :преподаватель %><br>
    <%= f.text_field :teacher %>
  </p>
  
  <p>
    <%= f.label :день_недели %><br>
    <%= f.select :day, options_for_select([["Понедельник", 1],
        ["Вторник", 2],
        ["Среда", 3],
        ["Четверг", 4],
        ["Пятница", 5],
        ["Суббота", 6]]) %>
  </p>
 
  <p>
    <%= f.label :начало_пары %><br>
    <%= f.text_field :start, :placeholder => "hh:mm" %>
  </p>
 
  <p>
    <%= f.label :окончание_пары %><br>
    <%= f.text_field :end, :placeholder => "hh:mm" %>
  </p>

  <%= f.hidden_field :group_id, :value => @group.id%>
 
  <p>
    <%= f.submit :сохранить%>
  </p>
<% end %>

<%= link_to 'Назад', group_path(@group) %>

app/views/lessons/show.html.erb
<p>
  <h1><%= @lesson.name%></h1><br>
  Преподаватель: <%= @lesson.teacher%><br>
  Начало пары: <%= @lesson.start %><br>
  Окончание пары: <%= @lesson.end %><br>
  День недели: <%= @days[@lesson.day - 1] %><br>
</p>

<%= link_to 'Вернуться к группе', group_path(@group) %>
<%= link_to 'Редактировать', edit_lesson_path(@lesson) %>

app/views/search/by_group.html.erb
<h1>Поиск расписания по группам </h1>
<%= link_to 'Перейти к списку факультетов', facultys_path %><br><br>

<%= form_tag(search_by_group_result_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
        <%= text_field_tag :search, params[:search], class: "span2", 
            placeholder: "Введите название группы"%>
        <%= submit_tag "Искать", :name => nil %>
    </div>
<% end %>

app/views/search/by_group_result.html.erb
<h1>Результат поиска</h1>
<%= link_to 'Перейти к списку факультетов', facultys_path %>&nbsp;&nbsp;&nbsp;
<%= link_to 'Поиск расписания по группам', search_by_group_path %><br><br>

<p>
  <h4>Группа <%= @group.name%></h4>
  <strong>Курс:</strong>
  <%= @group.cource %><br>
</p>

<strong>Расписание:</strong><br><br>

<strong>Понедельник:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 1 %>
        &nbsp;&nbsp;
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.teacher %></td>
        <td><%= lesson.start %></td>
        <td><%= lesson.end %></td>
        <td><%= @days[lesson.day - 1] %></td>
      </tr>
        <br>
    <% end %> 
<% end %>

<strong>Вторник:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 2 %>
        &nbsp;&nbsp;
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.teacher %></td>
        <td><%= lesson.start %></td>
        <td><%= lesson.end %></td>
        <td><%= @days[lesson.day - 1] %></td>
      </tr>
        <br>
    <% end %>
<% end %>

<strong>Среда:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 3 %>
        &nbsp;&nbsp;
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.teacher %></td>
        <td><%= lesson.start %></td>
        <td><%= lesson.end %></td>
        <td><%= @days[lesson.day - 1] %></td>
      </tr>
        <br>
    <% end %>
<% end %>

<strong>Четверг:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 4 %>
        &nbsp;&nbsp;
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.teacher %></td>
        <td><%= lesson.start %></td>
        <td><%= lesson.end %></td>
        <td><%= @days[lesson.day - 1] %></td>
      </tr>
        <br>
    <% end %>
<% end %>

<strong>Пятница:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 5 %>
        &nbsp;&nbsp;
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.teacher %></td>
        <td><%= lesson.start %></td>
        <td><%= lesson.end %></td>
        <td><%= @days[lesson.day - 1] %></td>
      </tr>
        <br>
    <% end %>
<% end %>

<strong>Суббота:</strong><br>
<% @group.lessons.each do |lesson| %> 
    <% if lesson.day == 6 %>
        &nbsp;&nbsp;
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.teacher %></td>
        <td><%= lesson.start %></td>
        <td><%= lesson.end %></td>
        <td><%= @days[lesson.day - 1] %></td>
      </tr>
        <br>
    <% end %>
<% end %>
</table>